[project]
name = "first-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harsh Agarwal", email = "harshagarwal31.creator@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp==3.4.4",
]

[project.scripts]
first-mcp = "first_mcp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
