[project]
name = "error-handling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harsh Agarwal", email = "harshagarwal31.creator@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=3.4.7",
    "pydantic>=2.13.5",
]

[project.scripts]
error-handling = "error_handling:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
